import Head from "next/head";
import Button from '@mui/material/Button';
import Box from '@mui/material/Box';
import Grid from '@mui/material/Unstable_Grid2';
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import Typography from '@mui/material/Typography';
import Icon from '../image/iconnavbar.png'
import TextField from '@mui/material/TextField';
import Page1 from "./Page1";
import Page2 from "./Page2";
import Page3 from "./Page3";
import Page4 from "./Page4";
import Page5 from "./Page5";
import Page6 from "./Page6";
import Page7 from "./Page7";
import Footer from "./Footer";
import Navbar from "./Navbar";


export default function Home() {


  return (
    <>
      <Head>
        <title>Web-Responsive</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
         <Navbar/>
        <Page1/>
        <Page2/>
        <Page3/>
        <Page4/>
        <Page5/>
        <Page6/>
        <Page7/>
        <Footer/>
      </main>
    </>
  );
}
